spring.application.name=dental-clinic-api

server.port=8080

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/dental_clinic_test_db
spring.datasource.username=postgres
spring.datasource.password=admin

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration